---
  - hosts: localhost
    become: true

    tasks:
      - name: TEST
        role_test:
          device_name: 'test1'
          disks: ['vdb']
          lvm_vg: 'foo'
          mount_point: '/opt/test1'
          size: '5g'
          #state: 'absent'
        register: test_results

      - name: Debug test results
        debug: var=test_results
